hatome/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include('messaging.urls', namespace = 'messaging')),
]

messaging/urls.py
"""hatome messaging URL Configuration
"""

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.mailbox, name = 'mailbox'),
    url(r'^new$', views.create_message, name = 'new'),
]

messaging/models.py
from random import choice, randint
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.contrib.auth.models import User

WORKER_TYPES = (
	('BASIC', 'Mail pigeon'),
	('HARDY', 'Guerrilla pigeon'),
	('EMU',   'Ausie pigeon'),
	('SUSHI', 'Sushi pigeon'),
)

MAX_SEED_VALUE = 2147483647

def generate_seed():
	return randint(0, MAX_SEED_VALUE)

def random_worker_type():
	return choice(WORKER_TYPES)

class Message(models.Model):
	sender = models.ForeignKey(User,
		help_text = 'User who sent the message',
		related_name = 'senders',
		on_delete = models.CASCADE)
	receiver = models.ForeignKey(User,
		help_text = 'User who should receive the message',
		related_name = 'receivers',
		on_delete = models.CASCADE)
	content = models.TextField(
		help_text = 'Please keep the message interesting <3',
		validators = [
			MinLengthValidator(
				200,
				message = 'Messages need at least 200 chars'),
			MaxLengthValidator(
				400,
				message = 'Messages need to be under 400 chars')])
	worker = models.CharField(
		help_text = 'Kind of pigeon worker that will deliver message',
		max_length = 5,
		choices = WORKER_TYPES,
		default = random_worker_type)
	sent_date = models.DateTimeField(
		help_text = 'When the message was sent',
		auto_now = True)
	seed = models.PositiveIntegerField(
		help_text = 'Seed to use when generating events',
		default = generate_seed)
	events_seen = models.PositiveIntegerField(
		help_text = 'Amount of events that sender has seen',
		default = 0,
		editable = False)

	def __str__(self):
		return "Message<{}, {}, {}, {}, {}>".format(
			self.sender, self.receiver, self.worker,
			self.sent_date, self.seed)

messaging/forms.py
from django.forms import ModelForm

from .models import Message

class MessageForm(ModelForm):
	class Meta:
		model = Message
		fields = ['content']

messaging/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .models import Message
from .forms import MessageForm

def mailbox(request):
	messages = Message.objects.filter()
	return render(request, 'messaging/mailbox.html', { 'messages': messages })

def create_message(request):
	if request.method == 'POST':
		form = MessageForm(request.POST)
		if form.is_valid():
			message = form.save(commit = False)
			message.sender = request.user
			message.receiver = request.user # CHANGE THIS LATER
			message.save()
			# Events won't be stored, call them every time
			# when drawing templates
			return render(request, 'messaging/confirmation.html', { })
	else:
		form = MessageForm()
	return render(request, 'messaging/create_message.html', { 'form': form })

hatome/templates/hatome/base.html
{% load staticfiles %}
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Hatome Pigeon Delivery</title>
		<meta name="description" content="The most reliable pigeon carriers around!">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<style>
		    body {
		        padding-top: 50px;
		        padding-bottom: 20px;
		    }
		</style>
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		
		<script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'messaging:mailbox' %}">Hatome Delivery Serivce</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<form class="navbar-form navbar-right" role="form">
						<div class="form-group">
							<input type="text" placeholder="Email" class="form-control">
						</div>
						<div class="form-group">
							<input type="password" placeholder="Password" class="form-control">
						</div>
						<button type="submit" class="btn btn-success">Sign in</button>
					</form>
				</div><!--/.navbar-collapse -->
			</div>
		</nav>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div> <!-- /container -->
		<footer>
			<p>&copy; Hatome-Chan</p>
		</footer>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js" %}"><\/script>')</script>

		<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

messaging/templates/messaging/confirmation.html
<html>
	<head>
	</head>
	<body>
		<h1>Our trusty pigeons have received your letter!</h1>
	</body>
</html>

messaging/templates/messaging/create_message.html
{% extends 'hatome/base.html' %}
{% block content %}
	<form action="/messages/new" method="POST">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit"/>
	</form>
{% endblock %}

messaging/templates/messaging/mailbox.html
{% extends 'hatome/base.html' %}

{% block content %}
	<div class="panel-group" id="message-accordion">
	{% for message in messages %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#message-accordion" href="#collapse-{{ forloop.counter }}">{{ message.sender }}</a>
				</h4>
			</div>
			<div id="collapse-{{ forloop.counter }}" class="panel-collapse collapse">
				<div class="panel-body">
					<p1>{{ message.content }}</p1>
				</div>
			</div>
		</div>
	{% endfor %}
	</div>
{% endblock %}